import 'server-only';
import { supabaseAdmin } from '@/lib/supabase/admin';
import { siteConfigEn as siteConfig } from '@/lib/site-config';

// TODO: Future Phase 4B: replace manual wa.me link with real WhatsApp Cloud API once the restaurant owner provides official business credentials.
// TODO: Real automatic sending must use the restaurant owner’s approved WhatsApp Business account.

export function buildRestaurantOrderMessage(order: any, items: any[]): string {
  const shortId = order.id.slice(0, 8);
  
  let paymentLabel = 'Pending';
  if (order.payment_status === 'mock_paid' || order.status === 'paid') {
    paymentLabel = 'Mock Paid';
  } else if (order.payment_status === 'cash_on_delivery' || order.payment_provider === 'cash') {
    paymentLabel = 'Cash on Delivery';
  }

  const formattedItems = items && items.length > 0
    ? items.map(item => `${item.quantity}x ${item.item_name} - ${Number(item.price).toFixed(2)} JOD`).join('\n')
    : 'No item details recorded';

  const subtotalNum = Number(order.subtotal || 0).toFixed(2);
  const deliveryFeeNum = Number(order.delivery_fee || 0).toFixed(2);
  const totalNum = (Number(order.subtotal || 0) + Number(order.delivery_fee || 0)).toFixed(2);
  const notesText = order.notes && order.notes.trim() ? order.notes.trim() : 'No notes';
  
  const fulfillmentLabel = order.delivery_address === 'Pickup' ? 'Pickup' : 'Delivery';
  
  let branchSection = '';
  if (order.branch_name) {
    branchSection = `Branch:\n${order.branch_name}\n${order.branch_address || ''}\n`;
  }

  let deliverySection = '';
  if (fulfillmentLabel === 'Delivery') {
    deliverySection = `Delivery Location:\nAddress: ${order.delivery_address}\n`;
    if (order.delivery_map_url) {
      deliverySection += `Map: ${order.delivery_map_url}\n`;
      if (order.delivery_distance_km !== undefined && order.delivery_distance_km !== null) {
        deliverySection += `Distance: ${Number(order.delivery_distance_km).toFixed(1)} km\n`;
      }
      deliverySection += `Coordinates: ${order.delivery_lat}, ${order.delivery_lng}\n`;
    }
    deliverySection += `Note: ${notesText}\n`;
  } else {
    deliverySection = `Customer Note:\n${notesText}\n`;
  }

  let totalsSection = `Subtotal: ${subtotalNum} JOD\n`;
  if (fulfillmentLabel === 'Delivery') {
    totalsSection += `Delivery Fee: ${deliveryFeeNum} JOD\n`;
  }
  totalsSection += `Total: ${totalNum} JOD`;

  return `New order from Two Hundred Burger website

Order #: ${shortId}
Payment: ${paymentLabel}
Fulfillment: ${fulfillmentLabel}

${branchSection}
Customer:
Name: ${order.customer_name}
Phone: ${order.customer_phone}

${deliverySection}
Items:
${formattedItems}

${totalsSection}

Generated by website demo.`;
}

export function buildWhatsAppLink(phone: string, message: string): string {
  const cleanPhone = phone.replace(/[^0-9]/g, '');
  return `https://wa.me/${cleanPhone}?text=${encodeURIComponent(message)}`;
}

export async function createRestaurantNotificationForOrder(orderId: string) {
  try {
    // 1. Idempotency Check: if notification already exists, return it
    const { data: existingNotification } = await supabaseAdmin
      .from('restaurant_notifications')
      .select('*')
      .eq('order_id', orderId)
      .eq('notification_type', 'new_order')
      .maybeSingle();

    if (existingNotification) {
      return existingNotification;
    }

    // 2. Fetch order details
    const { data: order, error: orderError } = await supabaseAdmin
      .from('orders')
      .select('*')
      .eq('id', orderId)
      .single();

    if (orderError || !order) {
      console.error('Notification creation failed: order not found', orderId, orderError);
      return null;
    }

    // 3. Eligibility Check: only create for paid mock card orders or Cash on Delivery
    const isMockPaid = order.payment_status === 'mock_paid' || (order.status === 'paid' && order.payment_provider === 'mock');
    const isCashOnDelivery = order.payment_status === 'cash_on_delivery' || order.payment_provider === 'cash';

    if (!isMockPaid && !isCashOnDelivery) {
      console.log(`Order ${orderId} is not eligible for restaurant notification (status: ${order.status}, payment_status: ${order.payment_status})`);
      return null;
    }

    // 4. Fetch order items
    const { data: items } = await supabaseAdmin
      .from('order_items')
      .select('*')
      .eq('order_id', orderId);

    // 5. Generate message & wa_link
    const restaurantPhone = process.env.RESTAURANT_WHATSAPP_NUMBER || siteConfig.whatsappNumber || '962790444939';
    const message = buildRestaurantOrderMessage(order, items || []);
    const waLink = buildWhatsAppLink(restaurantPhone, message);
    const mode = process.env.NOTIFICATION_MODE || 'manual';

    // 6. Insert notification record
    const { data: newNotification, error: insertError } = await supabaseAdmin
      .from('restaurant_notifications')
      .insert({
        order_id: orderId,
        notification_type: 'new_order',
        channel: 'whatsapp',
        mode: mode,
        status: 'generated',
        restaurant_phone: restaurantPhone,
        message: message,
        wa_link: waLink,
      })
      .select('*')
      .single();

    if (insertError) {
      // If concurrent request inserted it first (unique constraint violation)
      if (insertError.code === '23505') {
        const { data: fallbackNotification } = await supabaseAdmin
          .from('restaurant_notifications')
          .select('*')
          .eq('order_id', orderId)
          .eq('notification_type', 'new_order')
          .single();
        return fallbackNotification;
      }
      console.error('Failed to insert restaurant notification:', insertError);
      return null;
    }

    return newNotification;
  } catch (err) {
    console.error('Error in createRestaurantNotificationForOrder:', err);
    return null;
  }
}
